
ALTER TABLE PUBLIC.EMPLOYEE
ADD CONSTRAINT "EMPLOYEE_DEPARTMENT_ID_fk"
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES PUBLIC.DEPARTMENT(ID)
        ON UPDATE CASCADE;

ALTER TABLE PUBLIC.EMPLOYEE
ADD CONSTRAINT "EMPLOYEE_PROJECT_ID_fk"
    FOREIGN KEY (PROJECT_ID) REFERENCES PUBLIC.PROJECT(ID)
        ON UPDATE CASCADE;